title: NULS
subtitle: "NULS is a global blockchain open-source project which is a highly customizable modular blockchain infrastructure."
description: "NULS developer site. Power by HEXO."
author: NULS
language: en
timezone: UTC

url: https://nuls.io
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: nuls
deploy:
  type: git
  repo: git@github.com:nuls-io/nuls-io.git

highlight:
  enable: true
  line_number: true

twitter: nulsservice
reddit: r/nulsservice/
telegram: Nulsio
steemit: nuls
github: nuls-io/nuls
facebook: nulscommunity/
slack: t/nuls/shared_invite/enQtMjQ4MTM4ODAyNTI4LWJjNGMwYTE0YjRlYmFlZGUwM2JhOGE4MDIwZmE4MzA2MDg1YzUyMmVkN2RhZjkyNWMzZjY5ZDU5ZmViMjZjNGQ
gitter: nuls_io
